Models/ErrorViewModel.cs
namespace Car_Insurance_VS22.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Insuree.cs
namespace Car_Insurance_VS22.Models
{
	public class Insuree
	{
		public Guid Id { get; set; }
		public required string FirstName { get; set; }
		public required string LastName { get; set; }
		public required string EmailAddress { get; set; }
		public DateOnly DateOfBirth { get; set; }
		public required string CarYear { get; set; }
		public required string CarMake { get; set; }
		public required string CarModel { get; set; }
		public required string DUI { get; set; }
		public required string SpeedingTickets { get; set; }
		public required string CoverageType { get; set; }

		public required double Quote { get; set; }
		
	}
}

Models/InsureeQuoteAdminModel.cs
namespace Car_Insurance_VS22.Models
{
    public class InsureeQuoteAdminModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public decimal Quote { get; set; }
    }
}

Controllers/HomeController.cs
using Car_Insurance_VS22.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Car_Insurance_VS22.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/InsureesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Car_Insurance_VS22.Data;
using Car_Insurance_VS22.Models;
using System.ComponentModel.DataAnnotations;

namespace Car_Insurance_VS22.Controllers
{
    public class InsureesController : Controller
    {
        private readonly QuoteContext _context;

        public 
            InsureesController(QuoteContext context)
        {
            _context = context;
        }

        //method to calculate a quote
        private decimal CalculateQuote(Insuree insuree)
        {
            Double Quote = 50;
            var today = DateTime.Today;
            var age = today.Year - insuree.DateOfBirth.Year;
            //how age affects quote
            if (age <= 18) { Quote += 100; }
            if (age > 18 && age < 26) { Quote += 50; }
            if (age >= 26) { Quote += 25; }

            //how car year affects quote
            int carYearNum = int.Parse(insuree.CarYear);
            if (carYearNum < 2000) { Quote += 25; }
            if (carYearNum > 2015) { Quote += 25; }

            //how car make & model affects quote
            if (insuree.CarMake.ToLower().Equals("porsche")) { Quote += 25; }
            if (insuree.CarModel.ToLower().Contains("carrera")) { Quote += 25; }

            //how speeding tickets affect quote
            int numOfTickets = int.Parse(insuree.SpeedingTickets);
            if (numOfTickets > 0) { Quote += (numOfTickets * 10); }

            //how DUI affects quote
            int numOfDUI = int.Parse(insuree.DUI);
            if (numOfDUI > 0) { Quote *= 1.25; }

            //how full coverage affects quote
            if (insuree.CoverageType.ToLower().Equals("full")) { Quote *= 1.5; }

            return (decimal)Quote;
        }

        // GET: Insurees/Admin
        public async Task<IActionResult> Admin()
        {
            var insurees = await _context.Insuree.ToListAsync();
            var insureeQuotes = insurees.Select(i => new InsureeQuoteAdminModel
            {
                FirstName = i.FirstName,
                LastName = i.LastName,
                EmailAddress = i.EmailAddress,
                Quote = CalculateQuote(i)
            }).ToList();

            return View(insureeQuotes);
        }


        // GET: Insurees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Insuree.ToListAsync());
        }

        // GET: Insurees/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var insuree = await _context.Insuree
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insuree == null)
            {
                return NotFound();
            }

            return View(insuree);
        }

        // GET: Insurees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Insurees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageType,Quote")] Insuree insuree)
        {



            if (ModelState.IsValid)
            {
                insuree.Id = Guid.NewGuid();
                insuree.Quote = (double)CalculateQuote(insuree);
                _context.Add(insuree);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Success), new { id = insuree.Id });
            }
            return View(insuree);
        }

        // GET: Insurees/Success/5
        public async Task<IActionResult> Success(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var insuree = await _context.Insuree.FirstOrDefaultAsync(m => m.Id == id);
            if (insuree == null)
            {
                return NotFound();
            }

            return View(insuree);
        }

        // GET: Insurees/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var insuree = await _context.Insuree.FindAsync(id);
            if (insuree == null)
            {
                return NotFound();
            }
            return View(insuree);
        }

        // POST: Insurees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageType,Quote")] Insuree insuree)
        {
            if (id != insuree.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(insuree);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InsureeExists(insuree.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(insuree);
        }

        // GET: Insurees/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var insuree = await _context.Insuree
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insuree == null)
            {
                return NotFound();
            }

            return View(insuree);
        }

        // POST: Insurees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var insuree = await _context.Insuree.FindAsync(id);
            if (insuree != null)
            {
                _context.Insuree.Remove(insuree);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InsureeExists(Guid id)
        {
            return _context.Insuree.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1>Welcome to Awesome Insurance</h1>
    <p>To generate a quote for a monthly premium, please click the 'Create New Insuree' button below</p>

</div>
<div class="text-center">
<p>
    @Html.ActionLink("Create New Insuree", "Create", "Insurees", null, new { @class = "btn btn-primary" })
</p>
</div>

Views/Insurees/Admin.cshtml
@model IEnumerable<Car_Insurance_VS22.Models.InsureeQuoteAdminModel>

@{
    ViewData["Title"] = "Admin";
}

<h1>Admin View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quote)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quote)
            </td>

        </tr>
}
    </tbody>
</table>

Views/Insurees/Create.cshtml
@model Car_Insurance_VS22.Models.Insuree

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Insuree</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarYear" class="control-label"></label>
                <input asp-for="CarYear" class="form-control" />
                <span asp-validation-for="CarYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarMake" class="control-label"></label>
                <input asp-for="CarMake" class="form-control" />
                <span asp-validation-for="CarMake" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModel" class="control-label"></label>
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DUI" class="control-label"></label>
                <input asp-for="DUI" class="form-control" />
                <span asp-validation-for="DUI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeedingTickets" class="control-label"></label>
                <input asp-for="SpeedingTickets" class="form-control" />
                <span asp-validation-for="SpeedingTickets" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoverageType" class="control-label"></label>
                <input asp-for="CoverageType" class="form-control" />
                <span asp-validation-for="CoverageType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Insurees/Delete.cshtml
@model Car_Insurance_VS22.Models.Insuree

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Insuree</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarMake)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarMake)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarModel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DUI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DUI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeedingTickets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeedingTickets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoverageType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoverageType)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Insurees/Details.cshtml
@model Car_Insurance_VS22.Models.Insuree

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Insuree</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarMake)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarMake)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarModel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DUI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DUI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpeedingTickets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpeedingTickets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoverageType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoverageType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quote)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quote)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Insurees/Edit.cshtml
@model Car_Insurance_VS22.Models.Insuree

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Insuree</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarYear" class="control-label"></label>
                <input asp-for="CarYear" class="form-control" />
                <span asp-validation-for="CarYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarMake" class="control-label"></label>
                <input asp-for="CarMake" class="form-control" />
                <span asp-validation-for="CarMake" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModel" class="control-label"></label>
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DUI" class="control-label"></label>
                <input asp-for="DUI" class="form-control" />
                <span asp-validation-for="DUI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpeedingTickets" class="control-label"></label>
                <input asp-for="SpeedingTickets" class="form-control" />
                <span asp-validation-for="SpeedingTickets" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoverageType" class="control-label"></label>
                <input asp-for="CoverageType" class="form-control" />
                <span asp-validation-for="CoverageType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Insurees/Index.cshtml
@model IEnumerable<Car_Insurance_VS22.Models.Insuree>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarMake)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CarModel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DUI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpeedingTickets)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CoverageType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quote)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarMake)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarModel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DUI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpeedingTickets)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CoverageType)
            </td>
            <th>
                @Html.DisplayNameFor(modelItem => item.Quote)
            </th>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Insurees/Success.cshtml
@model Car_Insurance_VS22.Models.Insuree
@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>

<p>Congratulations, @Model.FirstName @Model.LastName!</p>
<p>Your quote for a monthly payment is: <strong>@Model.Quote</strong></p>
<a href="@Url.Action("Index", "Insurees")">Back to List</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car_Insurance_VS22</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Car_Insurance_VS22.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Car_Insurance_VS22</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Car_Insurance_VS22 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>